### ISSUE TITLE
broken after patch?

### ISSUE THREAD

**Issue by AlbertFnWesker** [eleval/BhdTool#8]
So I tried using this today and the game wont launch, I had no issues last week. Someone else I know tried today and it wouldn't launch for them either, apparently there may have been a patch to the game within the last few days? its what im hearing, not sure.

**Comment by eleval** [comment]
Hello!

Yes, the tool has been broken by the game's latest update as they've recompiled the executable, meaning memory addresses have changed.
I'm currently not home until mid august so I unfortunately cannot fix the issue until then :/
I'll work on it as soon as I get back.

**Comment by eleval** [comment]
It should be fixed with version 1.2 !
https://github.com/eleval/BhdTool/releases/tag/v1.2

I'm waiting for Pessimism to test it a bit before I post about it on SRC so everyone's aware.
